"""init

Revision ID: 7543ac39fbe6
Revises: e8797d9410fe
Create Date: 2026-05-27 12:49:04.256675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7543ac39fbe6'
down_revision: Union[str, Sequence[str], None] = 'e8797d9410fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_jobs', sa.Column('file_hash', sa.Text(), nullable=True))
    op.create_index(op.f('ix_document_jobs_file_hash'), 'document_jobs', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_jobs_file_hash'), table_name='document_jobs')
    op.drop_column('document_jobs', 'file_hash')
    # ### end Alembic commands ###
