"""init

Revision ID: af7d8bd6a1cd
Revises: 
Create Date: 2026-05-16 23:20:07.384369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af7d8bd6a1cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clauses_clause_id'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_id'), table_name='clauses')
    op.drop_table('clauses')
    op.add_column('hs_master', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('hs_master', sa.Column('product_name', sa.String(length=255), nullable=True))
    op.add_column('hs_master', sa.Column('tr_id', sa.Integer(), nullable=True))
    op.add_column('hs_master', sa.Column('tr_name', sa.String(length=255), nullable=True))
    op.add_column('hs_master', sa.Column('std_id', sa.Integer(), nullable=True))
    op.add_column('hs_master', sa.Column('std_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'hs_master', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'hs_master', 'technical_regulations', ['tr_id'], ['id'])
    op.create_foreign_key(None, 'hs_master', 'standards', ['std_id'], ['id'])
    op.drop_column('ksasaleems', 'sub_folder_name')
    op.drop_column('ksasaleems', 'folder_name')
    op.add_column('products', sa.Column('tr_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('tr_name', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('std_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('std_name', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=True)
    op.create_foreign_key(None, 'products', 'technical_regulations', ['tr_id'], ['id'])
    op.create_foreign_key(None, 'products', 'standards', ['std_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.drop_column('products', 'std_name')
    op.drop_column('products', 'std_id')
    op.drop_column('products', 'tr_name')
    op.drop_column('products', 'tr_id')
    op.add_column('ksasaleems', sa.Column('folder_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ksasaleems', sa.Column('sub_folder_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hs_master', type_='foreignkey')
    op.drop_constraint(None, 'hs_master', type_='foreignkey')
    op.drop_constraint(None, 'hs_master', type_='foreignkey')
    op.drop_column('hs_master', 'std_name')
    op.drop_column('hs_master', 'std_id')
    op.drop_column('hs_master', 'tr_name')
    op.drop_column('hs_master', 'tr_id')
    op.drop_column('hs_master', 'product_name')
    op.drop_column('hs_master', 'product_id')
    op.create_table('clauses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clause_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('standard', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('field', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rule_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mandatory', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('market', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rule_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('clauses_pkey')),
    sa.UniqueConstraint('rule_hash', name=op.f('clauses_rule_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_clauses_id'), 'clauses', ['id'], unique=False)
    op.create_index(op.f('ix_clauses_clause_id'), 'clauses', ['clause_id'], unique=True)
    # ### end Alembic commands ###
