"""init

Revision ID: da0710a42c48
Revises: 
Create Date: 2026-05-21 10:42:57.130563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0710a42c48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tr_rerquirements', sa.Column('req_raw_data', sa.Text(), nullable=True))
    op.add_column('tr_rerquirements', sa.Column('tr_req_clauses', sa.JSON(), nullable=True))
    op.add_column('tr_rerquirements', sa.Column('tr_toc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tr_rerquirements', 'tr_tocs', ['tr_toc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tr_rerquirements', type_='foreignkey')
    op.drop_column('tr_rerquirements', 'tr_toc_id')
    op.drop_column('tr_rerquirements', 'tr_req_clauses')
    op.drop_column('tr_rerquirements', 'req_raw_data')
    # ### end Alembic commands ###
