"""init

Revision ID: e8797d9410fe
Revises: da0710a42c48
Create Date: 2026-05-27 12:11:04.190153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8797d9410fe'
down_revision: Union[str, Sequence[str], None] = 'da0710a42c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_job_items', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('document_job_items', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_job_items', 'error_message')
    op.drop_column('document_job_items', 'retry_count')
    # ### end Alembic commands ###
